import { NodeData, ResourceType } from './types';

export const INITIAL_MONEY = 25000000;
export const LOAN_AMOUNT = 5000000;
export const LOAN_INTEREST_RATE = 0.01; // 1% per second

export interface NodeTemplate {
  type: string;
  label: string;
  cost: number;
  upkeepCost: number;
  pollution: number;
  powerRequired: number;
  laborRequired: number;
  laborProduced: number;
  capacity?: Partial<Record<ResourceType, number>>;
  outputRate?: Partial<Record<ResourceType, number>>;
  inputRequirements?: Partial<Record<ResourceType, number>>;
  transferRate?: number;
  color: string;
  category: 'Power' | 'Factories' | 'Logistics' | 'Population' | 'Facilities' | 'Resource';
  resourceDraw?: number;
}

export const NODE_TEMPLATES: Record<string, NodeTemplate> = {
  // Power
  'coal-power': {
    type: 'coal-power',
    label: 'Coal Power Plant',
    cost: 250000,
    upkeepCost: 500,
    pollution: 20,
    powerRequired: 0,
    laborRequired: 20,
    laborProduced: 0,
    inputRequirements: { 'Coal': 2 },
    outputRate: { 'Power': 100 },
    capacity: { 'Coal': 200 },
    transferRate: 20,
    color: 'bg-yellow-500',
    category: 'Power',
    resourceDraw: 0,
  },
  'oil-power': {
    type: 'oil-power',
    label: 'Oil Power Plant',
    cost: 600000,
    upkeepCost: 6000,
    pollution: 15,
    powerRequired: 0,
    laborRequired: 15,
    laborProduced: 0,
    inputRequirements: { 'Oil': 3 },
    outputRate: { 'Power': 250 },
    capacity: { 'Oil': 50 },
    transferRate: 15,
    color: 'bg-yellow-600',
    category: 'Power',
    resourceDraw: 0,
  },
  'solar-farm': {
    type: 'solar-farm',
    label: 'Solar Farm',
    cost: 1500000,
    upkeepCost: 1000,
    pollution: 0,
    powerRequired: 0,
    laborRequired: 5,
    laborProduced: 0,
    outputRate: { 'Power': 50 },
    transferRate: 5,
    color: 'bg-yellow-400',
    category: 'Power',
    resourceDraw: 0,
  },
  'substation': {
    type: 'substation',
    label: 'Substation',
    cost: 50000,
    upkeepCost: 250,
    pollution: 0,
    powerRequired: 5,
    laborRequired: 2,
    laborProduced: 0,
    transferRate: 20,
    color: 'bg-yellow-700',
    category: 'Power',
    resourceDraw: 0,
  },
  
  // Factories
  'farm': {
    type: 'farm',
    label: 'Farm',
    cost: 400000,
    upkeepCost: 500,
    pollution: 2,
    powerRequired: 10,
    laborRequired: 15,
    laborProduced: 0,
    outputRate: { 'Food': 5 },
    capacity: { 'Food': 100 },
    transferRate: 10,
    color: 'bg-orange-400',
    category: 'Factories',
  },
  'processing-plant': {
    type: 'processing-plant',
    label: 'Processing Plant',
    cost: 750000,
    upkeepCost: 1500,
    pollution: 25,
    powerRequired: 50,
    laborRequired: 40,
    laborProduced: 0,
    inputRequirements: { 'Minerals': 2, 'Wood': 2 },
    outputRate: { 'Processed Goods': 5 },
    capacity: { 'Minerals': 50, 'Wood': 50, 'Processed Goods': 100 },
    transferRate: 10,
    color: 'bg-orange-600',
    category: 'Factories',
  },
  'waste-treatment': {
    type: 'waste-treatment',
    label: 'Waste Treatment',
    cost: 1000000,
    upkeepCost: 7500,
    pollution: -50, // Reduces global pollution
    powerRequired: 80,
    laborRequired: 30,
    laborProduced: 0,
    inputRequirements: { 'Waste': 10 },
    capacity: { 'Waste': 200 },
    transferRate: 20,
    color: 'bg-orange-800',
    category: 'Factories',
  },
  
  // Logistics
  'warehouse': {
    type: 'warehouse',
    label: 'Warehouse',
    cost: 200000,
    upkeepCost: 500,
    pollution: 1,
    powerRequired: 10,
    laborRequired: 10,
    laborProduced: 0,
    capacity: { 'Processed Goods': 1000, 'Food': 1000, 'Wood': 1000, 'Minerals': 1000, 'Coal': 1000, 'Oil': 1000, 'Water': 1000, 'Waste': 1000 },
    transferRate: 50,
    color: 'bg-blue-500',
    category: 'Logistics',
  },
  'shop': {
    type: 'shop',
    label: 'Shop',
    cost: 300000,
    upkeepCost: 500,
    pollution: 2,
    powerRequired: 20,
    laborRequired: 15,
    laborProduced: 0,
    inputRequirements: {},
    capacity: { 'Processed Goods': 200, 'Food': 200 },
    transferRate: 20,
    color: 'bg-blue-600',
    category: 'Logistics',
  },
  
  // Population
  'residential': {
    type: 'residential',
    label: 'Residential Zone',
    cost: 500000,
    upkeepCost: 500,
    pollution: 5,
    powerRequired: 30,
    laborRequired: 0,
    laborProduced: 200,
    inputRequirements: { 'Processed Goods': 1, 'Food': 1, 'Water': 1 },
    outputRate: { 'Waste': 1 },
    capacity: { 'Processed Goods': 50, 'Food': 50, 'Water': 50, 'Waste': 50 },
    transferRate: 5,
    color: 'bg-purple-500',
    category: 'Population',
  },
  
  // Facilities
  'city-hall': {
    type: 'city-hall',
    label: 'City Hall',
    cost: 0,
    upkeepCost: 1000,
    pollution: 0,
    powerRequired: 50,
    laborRequired: 50,
    laborProduced: 0,
    transferRate: 10,
    color: 'bg-slate-800',
    category: 'Facilities',
  },
  'airport': {
    type: 'airport',
    label: 'Airport',
    cost: 5000000,
    upkeepCost: 50000,
    pollution: 30,
    powerRequired: 150,
    laborRequired: 100,
    laborProduced: 0,
    transferRate: 100,
    color: 'bg-slate-600',
    category: 'Facilities',
  },
  'hospital': {
    type: 'hospital',
    label: 'Hospital',
    cost: 4000000,
    upkeepCost: 30000,
    pollution: 0,
    powerRequired: 100,
    laborRequired: 80,
    laborProduced: 0,
    transferRate: 50,
    color: 'bg-red-500',
    category: 'Facilities',
  },
  
  // Resources (Not buildable)
  'forest': {
    type: 'forest',
    label: 'Forest',
    cost: 0,
    upkeepCost: 0,
    pollution: -10,
    powerRequired: 0,
    laborRequired: 0,
    laborProduced: 0,
    outputRate: { 'Wood': 2 },
    capacity: { 'Wood': 100 },
    transferRate: 5,
    color: 'bg-green-600',
    category: 'Resource',
  },
  'quarry': {
    type: 'quarry',
    label: 'Quarry',
    cost: 0,
    upkeepCost: 0,
    pollution: 10,
    powerRequired: 0,
    laborRequired: 0,
    laborProduced: 0,
    outputRate: { 'Minerals': 2 },
    capacity: { 'Minerals': 100 },
    transferRate: 5,
    color: 'bg-stone-600',
    category: 'Resource',
  },
  'water-source': {
    type: 'water-source',
    label: 'Water Source',
    cost: 0,
    upkeepCost: 0,
    pollution: 0,
    powerRequired: 0,
    laborRequired: 0,
    laborProduced: 0,
    outputRate: { 'Water': 5 },
    capacity: { 'Water': 200 },
    transferRate: 10,
    color: 'bg-cyan-500',
    category: 'Resource',
  },
  'coal-deposit': {
    type: 'coal-deposit',
    label: 'Coal Deposit',
    cost: 0,
    upkeepCost: 0,
    pollution: 15,
    powerRequired: 0,
    laborRequired: 0,
    laborProduced: 0,
    outputRate: { 'Coal': 3 },
    capacity: { 'Coal': 100 },
    transferRate: 20,
    color: 'bg-gray-800',
    category: 'Resource',
  },
  'oil-reserve': {
    type: 'oil-reserve',
    label: 'Oil Reserve',
    cost: 0,
    upkeepCost: 0,
    pollution: 20,
    powerRequired: 0,
    laborRequired: 0,
    laborProduced: 0,
    outputRate: { 'Oil': 3 },
    capacity: { 'Oil': 100 },
    transferRate: 5,
    color: 'bg-black',
    category: 'Resource',
  },
};
